RANSAC:
  RANSAC_DistThreshold : 0.25
  RANSAC_MinInliers : 0.5
  RANSAC_PlaneVectorThreshold : 0.2

Downsampling:
  KSearch: 10
  leafSize: 0.05

Clustering:
  MinSizeOfCluster: 50
  NumberOfNeighbours : 30
  SmoothnessThreshold : 2
  CurvatureThreshold : 5


pointPitch : 20
minPlaneHeight : 0.2

Combine:
  minimumEdgeDist : 1.0
  minPlanesDist : 0.4
  minAngle_normalDiff : 10.0

SmoothNoise:
  K : 50
  beta : 3

View:
  original         : true
  smoothNoise      : false
  densityFilter    : false
  2D               : false
  BiggestComponent : false
  hull             : false
  extractLine      : false
  linkedEdges      : true
  BeamCube         : true
  BeamCubeEach     : false


DensityFilter:
  alpha2: 1.0
  leafSize: 0.1

ComputeHull:
  alpha: 0.1


RegionGrow2D:
  serarchRadius : 0.3
  normalTh : 5

BeamRecons:
  isExist : false
  RANSACDistTh : 1
  # for the edge we found for on possible beam, we search its surrounding points along z axis
  EdgeZDist : 0.1
  # the num of points in the cube over the size of cube  (l*h / rho^2) / (2*d*l*h / rho^2) = 1/2 * d
  cubeNumPtsRatio : 0.5

